fix: init process, but needs to fix socket
Error Message:
      > [binance-trade-observer-55f9db7845-dvk6h binance-trade-observer] thread 'main' panicked at /home/hyamamoto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9:
      > [binance-trade-observer-55f9db7845-dvk6h binance-trade-observer] Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.